// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	applicationv1alpha1 "github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha1"
	scheme "github.com/argoproj/argo-cd/v3/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ArgoCDConfigsGetter has a method to return a ArgoCDConfigInterface.
// A group's client should implement this interface.
type ArgoCDConfigsGetter interface {
	ArgoCDConfigs(namespace string) ArgoCDConfigInterface
}

// ArgoCDConfigInterface has methods to work with ArgoCDConfig resources.
type ArgoCDConfigInterface interface {
	Create(ctx context.Context, argoCDConfig *applicationv1alpha1.ArgoCDConfig, opts v1.CreateOptions) (*applicationv1alpha1.ArgoCDConfig, error)
	Update(ctx context.Context, argoCDConfig *applicationv1alpha1.ArgoCDConfig, opts v1.UpdateOptions) (*applicationv1alpha1.ArgoCDConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*applicationv1alpha1.ArgoCDConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*applicationv1alpha1.ArgoCDConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *applicationv1alpha1.ArgoCDConfig, err error)
	ArgoCDConfigExpansion
}

// argoCDConfigs implements ArgoCDConfigInterface
type argoCDConfigs struct {
	*gentype.ClientWithList[*applicationv1alpha1.ArgoCDConfig, *applicationv1alpha1.ArgoCDConfigList]
}

// newArgoCDConfigs returns a ArgoCDConfigs
func newArgoCDConfigs(c *ArgoprojV1alpha1Client, namespace string) *argoCDConfigs {
	return &argoCDConfigs{
		gentype.NewClientWithList[*applicationv1alpha1.ArgoCDConfig, *applicationv1alpha1.ArgoCDConfigList](
			"argocdconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *applicationv1alpha1.ArgoCDConfig { return &applicationv1alpha1.ArgoCDConfig{} },
			func() *applicationv1alpha1.ArgoCDConfigList { return &applicationv1alpha1.ArgoCDConfigList{} },
		),
	}
}
