// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	applicationv1alpha1 "github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha1"
	scheme "github.com/argoproj/argo-cd/v3/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ConfigurationsGetter has a method to return a ConfigurationInterface.
// A group's client should implement this interface.
type ConfigurationsGetter interface {
	Configurations(namespace string) ConfigurationInterface
}

// ConfigurationInterface has methods to work with Configuration resources.
type ConfigurationInterface interface {
	Create(ctx context.Context, configuration *applicationv1alpha1.Configuration, opts v1.CreateOptions) (*applicationv1alpha1.Configuration, error)
	Update(ctx context.Context, configuration *applicationv1alpha1.Configuration, opts v1.UpdateOptions) (*applicationv1alpha1.Configuration, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*applicationv1alpha1.Configuration, error)
	List(ctx context.Context, opts v1.ListOptions) (*applicationv1alpha1.ConfigurationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *applicationv1alpha1.Configuration, err error)
	ConfigurationExpansion
}

// configurations implements ConfigurationInterface
type configurations struct {
	*gentype.ClientWithList[*applicationv1alpha1.Configuration, *applicationv1alpha1.ConfigurationList]
}

// newConfigurations returns a Configurations
func newConfigurations(c *ArgoprojV1alpha1Client, namespace string) *configurations {
	return &configurations{
		gentype.NewClientWithList[*applicationv1alpha1.Configuration, *applicationv1alpha1.ConfigurationList](
			"configurations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *applicationv1alpha1.Configuration { return &applicationv1alpha1.Configuration{} },
			func() *applicationv1alpha1.ConfigurationList { return &applicationv1alpha1.ConfigurationList{} },
		),
	}
}
