// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha1"
	applicationv1alpha1 "github.com/argoproj/argo-cd/v3/pkg/client/clientset/versioned/typed/application/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeConfigurations implements ConfigurationInterface
type fakeConfigurations struct {
	*gentype.FakeClientWithList[*v1alpha1.Configuration, *v1alpha1.ConfigurationList]
	Fake *FakeArgoprojV1alpha1
}

func newFakeConfigurations(fake *FakeArgoprojV1alpha1, namespace string) applicationv1alpha1.ConfigurationInterface {
	return &fakeConfigurations{
		gentype.NewFakeClientWithList[*v1alpha1.Configuration, *v1alpha1.ConfigurationList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("configurations"),
			v1alpha1.SchemeGroupVersion.WithKind("Configuration"),
			func() *v1alpha1.Configuration { return &v1alpha1.Configuration{} },
			func() *v1alpha1.ConfigurationList { return &v1alpha1.ConfigurationList{} },
			func(dst, src *v1alpha1.ConfigurationList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ConfigurationList) []*v1alpha1.Configuration {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ConfigurationList, items []*v1alpha1.Configuration) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
