// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha1"
	applicationv1alpha1 "github.com/argoproj/argo-cd/v3/pkg/client/clientset/versioned/typed/application/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeArgoCDConfigs implements ArgoCDConfigInterface
type fakeArgoCDConfigs struct {
	*gentype.FakeClientWithList[*v1alpha1.ArgoCDConfig, *v1alpha1.ArgoCDConfigList]
	Fake *FakeArgoprojV1alpha1
}

func newFakeArgoCDConfigs(fake *FakeArgoprojV1alpha1, namespace string) applicationv1alpha1.ArgoCDConfigInterface {
	return &fakeArgoCDConfigs{
		gentype.NewFakeClientWithList[*v1alpha1.ArgoCDConfig, *v1alpha1.ArgoCDConfigList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("argocdconfigs"),
			v1alpha1.SchemeGroupVersion.WithKind("ArgoCDConfig"),
			func() *v1alpha1.ArgoCDConfig { return &v1alpha1.ArgoCDConfig{} },
			func() *v1alpha1.ArgoCDConfigList { return &v1alpha1.ArgoCDConfigList{} },
			func(dst, src *v1alpha1.ArgoCDConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ArgoCDConfigList) []*v1alpha1.ArgoCDConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ArgoCDConfigList, items []*v1alpha1.ArgoCDConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
