// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	applicationv1alpha1 "github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ArgoCDConfigLister helps list ArgoCDConfigs.
// All objects returned here must be treated as read-only.
type ArgoCDConfigLister interface {
	// List lists all ArgoCDConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*applicationv1alpha1.ArgoCDConfig, err error)
	// ArgoCDConfigs returns an object that can list and get ArgoCDConfigs.
	ArgoCDConfigs(namespace string) ArgoCDConfigNamespaceLister
	ArgoCDConfigListerExpansion
}

// argoCDConfigLister implements the ArgoCDConfigLister interface.
type argoCDConfigLister struct {
	listers.ResourceIndexer[*applicationv1alpha1.ArgoCDConfig]
}

// NewArgoCDConfigLister returns a new ArgoCDConfigLister.
func NewArgoCDConfigLister(indexer cache.Indexer) ArgoCDConfigLister {
	return &argoCDConfigLister{listers.New[*applicationv1alpha1.ArgoCDConfig](indexer, applicationv1alpha1.Resource("argocdconfig"))}
}

// ArgoCDConfigs returns an object that can list and get ArgoCDConfigs.
func (s *argoCDConfigLister) ArgoCDConfigs(namespace string) ArgoCDConfigNamespaceLister {
	return argoCDConfigNamespaceLister{listers.NewNamespaced[*applicationv1alpha1.ArgoCDConfig](s.ResourceIndexer, namespace)}
}

// ArgoCDConfigNamespaceLister helps list and get ArgoCDConfigs.
// All objects returned here must be treated as read-only.
type ArgoCDConfigNamespaceLister interface {
	// List lists all ArgoCDConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*applicationv1alpha1.ArgoCDConfig, err error)
	// Get retrieves the ArgoCDConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*applicationv1alpha1.ArgoCDConfig, error)
	ArgoCDConfigNamespaceListerExpansion
}

// argoCDConfigNamespaceLister implements the ArgoCDConfigNamespaceLister
// interface.
type argoCDConfigNamespaceLister struct {
	listers.ResourceIndexer[*applicationv1alpha1.ArgoCDConfig]
}
