// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	applicationv1alpha1 "github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ConfigurationLister helps list Configurations.
// All objects returned here must be treated as read-only.
type ConfigurationLister interface {
	// List lists all Configurations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*applicationv1alpha1.Configuration, err error)
	// Configurations returns an object that can list and get Configurations.
	Configurations(namespace string) ConfigurationNamespaceLister
	ConfigurationListerExpansion
}

// configurationLister implements the ConfigurationLister interface.
type configurationLister struct {
	listers.ResourceIndexer[*applicationv1alpha1.Configuration]
}

// NewConfigurationLister returns a new ConfigurationLister.
func NewConfigurationLister(indexer cache.Indexer) ConfigurationLister {
	return &configurationLister{listers.New[*applicationv1alpha1.Configuration](indexer, applicationv1alpha1.Resource("configuration"))}
}

// Configurations returns an object that can list and get Configurations.
func (s *configurationLister) Configurations(namespace string) ConfigurationNamespaceLister {
	return configurationNamespaceLister{listers.NewNamespaced[*applicationv1alpha1.Configuration](s.ResourceIndexer, namespace)}
}

// ConfigurationNamespaceLister helps list and get Configurations.
// All objects returned here must be treated as read-only.
type ConfigurationNamespaceLister interface {
	// List lists all Configurations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*applicationv1alpha1.Configuration, err error)
	// Get retrieves the Configuration from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*applicationv1alpha1.Configuration, error)
	ConfigurationNamespaceListerExpansion
}

// configurationNamespaceLister implements the ConfigurationNamespaceLister
// interface.
type configurationNamespaceLister struct {
	listers.ResourceIndexer[*applicationv1alpha1.Configuration]
}
